### ISSUE TITLE
[AN] Add contracts when network starts

### ISSUE THREAD

**Issue by paguos** [cp-ss2019/decentralized-energy-trading#57] opened 2019-05-10 17:12 UTC
**Background**
When the network starts some contracts should be deployed. It would be nice if this will happen in the background and no additional setup is required

**Acceptance Criteria**
Be able to deploy as many contracts as necessary when the blockchain network starts.

- [x] Implementation
- [x] Tests

**Comment by dakingha69** [comment] 2019-05-10 17:19
Related to / Duplicate of #56

**Comment by paguos** [comment] 2019-05-18 16:03
No need to implement this, all contracts will be deployed in the genesis file

**Closed** 2019-05-20 12:02 UTC
Labels: deprecated, enhancement, infrastructure
